### ISSUE TITLE
가상계좌 환불 시 오류 발생합니다.

### ISSUE THREAD

**Issue by limchangtaek** [kginicis-ts/INICIS-INIAPI#20]
안녕하세요. 굿스플로입니다.

가상계좌 전체환불 시 아래와 같은 오류가 발생합니다.

-url: https://iniapi.inicis.com/v2/pg/refund/vacct
- 전송데이터(일부 문자열을 "..."로 표기)
{
  "mid": "go....",
  "type": "refund",
  "timestamp": "1720398547908",
  "clientIp": "218.1.....",
  "hashData": "41a7ffc120aaf44b5db825827bb83adfb654c277267a9d8ffc328ddd97d749a75d0b6794033c500a5a0d519d58f9115eacfa5c1d888ded0ab2c3dfa4194f7998",
  "data": {
    "tid": "StdpayVBNKgo.....",
    "msg": "취소(테스트)",
    "refundAcctNum": "gFoQUQPPGwf7W9M.....",
    "refundBankCode": "03",
    "refundAcctName": "..."
  }
}

- 결과
{"resultCode":"ER0107","resultMsg":"XML 생성 오류"}

**Comment by ts-inicis** [comment]
상세 이력 확인을 위해 ER0107 오류가 발생 된 요청건에 대한 요청데이터 및 TID 정보를 ts@kggroup.co.kr로 전달부탁드립니다.
